version: "3"
services:
  web:
    build: ./docker/web
    ports:
      - "9000:80"
    volumes:
      - ./:/opt/car-search
    depends_on:
      - "db"
    environment:
      PYTHONUNBUFFERED: 0
    restart: unless-stopped
  db:
    image: postgres:11.1
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - "9001:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Ek9z32CDUg5xXOmoLYdo
      POSTGRES_DB: car-search
