version: "3"
services:
  web:
    build: ./docker/web
    ports:
      - "8000:8000"
    volumes:
      - ./:/opt/test-task
    depends_on:
      - "db"
    environment:
      PYTHONUNBUFFERED: 0
    restart: unless-stopped
  db:
    image: postgres:11.1
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - "9001:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Jv8rLsTUqyPau7q8Yamm
      POSTGRES_DB: test_products_task